#!/usr/bin/env node
const addJsonToUser = require('./lib/add-json-to-user');
const getJsonFromUser = require('./lib/show-json-to-user');
const listJsonFromUser = require('./lib/list-json-to-user');
const sumJsonFromUser = require('./lib/sum-json-from-user');
const parseJson = require('./lib/parse-json');


const [ ,, user, action, json ] = process.argv;
let promise = Promise.resolve();


if (user && json && action === 'add') promise = addJsonToUser(user, parseJson(json));
else if (json === undefined && user && action === 'list') promise = listJsonFromUser(user);
else if (json === undefined && user && action === 'sum')promise = sumJsonFromUser(user);
else if (json === undefined && user && action) promise = getJsonFromUser(user, action);


promise
    .catch(({ message }) => console.error(message))
    .then(() => process.exit(0));
